### PR TITLE
use git clone and tag for version

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by thelamer** [comment]
Can we symlink out the cache and stop chowning ? `/app/sickchill/gui/slick/cache`

**Comment by thelamer** [comment]
@aptalca you get some perm denied shit in the git tree but looks fucntional, did not full loop though.

**Comment by aptalca** [comment]
Yeah, that's because the app's trying to figure out the branch for updates but because we checkout the tag, the HEAD's detached

**Comment by thelamer** [comment]
No I was commenting on my removal of the chown and symlink of cache to config. 
I just loop tested everything short of actually downloading something I think we are ok to leave it as root

**Review by thelamer — APPROVED** [review]

**Comment by Leopere** [comment]
Tested `lspipepr/sickchill:amd64-v2020.04.22-4-pkg-afe6ddd1-pr-17` and got 
```
chill_sickchill.1.p5fgo2zgqm8w@s    | 16:35:35 ERROR::MAIN :: [3e12397] git symbolic-ref -q HEAD returned :
chill_sickchill.1.p5fgo2zgqm8w@s    | None
chill_sickchill.1.p5fgo2zgqm8w@s    | 16:35:46 INFO::MAIN :: 260437: Unable to find IMDb show info in the database
chill_sickchill.1.p5fgo2zgqm8w@s    | 16:35:47 INFO::MAIN :: Starting SickChill [] using '/config/config.ini'
chill_sickchill.1.p5fgo2zgqm8w@s    | 16:35:47 INFO::WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
chill_sickchill.1.p5fgo2zgqm8w@s    | 16:35:47 INFO::CHECKVERSION :: Checking for updates using GIT
chill_sickchill.1.p5fgo2zgqm8w@s    | 16:35:47 ERROR::CHECKVERSION :: [3e12397] git symbolic-ref -q HEAD returned :
chill_sickchill.1.p5fgo2zgqm8w@s    | None
chill_sickchill.1.p5fgo2zgqm8w@s    | 16:35:47 ERROR::CHECKVERSION :: [757fa1f] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: Permission denied
chill_sickchill.1.p5fgo2zgqm8w@s    | None
chill_sickchill.1.p5fgo2zgqm8w@s    | 16:35:47 ERROR::CHECKVERSION :: [757fa1f] git fetch origin --prune returned code 255, treating as error : error: cannot open .git/FETCH_HEAD: Permission denied
chill_sickchill.1.p5fgo2zgqm8w@s    | None
chill_sickchill.1.p5fgo2zgqm8w@s    | 16:35:47 WARNING::CHECKVERSION :: Unable to contact github, can't check for update
```
which indicated that the internal LSIO updater is not enabled for this container but the app booted fine and was a nondestructive boot.

I'd approve this test as passed.

**Pull request merged**
